#!/usr/bin/env bash

#    ____ ____  ______        ____  __ 
#   | __ ) ___||  _ \ \      / /  \/  |  - z0mbi3
#   |  _ \___ \| |_) \ \ /\ / /| |\/| |  - https://github.com/gh0stzk/dotfiles
#   | |_) |__) |  __/ \ V  V / | |  | |  - z0mbi3.zk@protonmail.com
#   |____/____/|_|     \_/\_/  |_|  |_|
#                                    z0mbi3 config..


########### Def vars

export RICETHEME=$(<$HOME/.config/bspwm/rice.cfg)
PATH="$HOME/.config/bspwm/scripts:$PATH"
bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/rices/$RICETHEME/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

## You can edit this.
BSPWM_BORDER='1'
BSPWM_GAP='8'

########### Functions

function launch() {
  local running
  running="$(pgrep -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ReloadTerms() {
  cat $HOME/.config/bspwm/rices/$RICETHEME/alacrittyrc > $HOME/.config/alacritty/alacritty.yml
}

function SetBspwmConf() {
	bspc config border_width "$1"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
	bspc config window_gap "$BSPWM_GAP"
}

########### Workspaces

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
		let name++
	done
}

workspaces

########### Launch The Rice!!

case $RICETHEME in

		meimei)
		
		  SetBspwmConf '1' 0 0 "#1A1B26" "#9ece6a" "#0A9CF5" "#FBC02D" 0 0 '8'
		  		  
		  killeww
		  launch polybar -q meimei-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		  
		emilia)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#414868" "#c0caf5" "#bb9af7" "#7aa2f7" 5 5 "$BSPWM_GAP"
		  		  
		  killeww
		  launch polybar -q emi-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
			
		jan)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q main -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		    
		aline)
		
		  SetBspwmConf "$BSPWM_BORDER" 55 5 "#ca9ee6" "#ca9ee6" "#8CAAEE" "#E78284" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q aline-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-light
		  
		  ;;
		  
		isabel)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 45 "#b8bfe5" "#b8bfe5" "#7560d3" "#81ae5f" 5 5 "$BSPWM_GAP" 
		  
		  killeww
		  launch polybar -q isa-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		cynthia)
		
		  SetBspwmConf "$BSPWM_BORDER" 50 50 "#543f66" "#543f66" "#465b80" "#3f5273" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q cyn-bar -c ${polydir}/config.ini
		  polybar -q cyn-bar2 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		silvia)
		
		  SetBspwmConf "$BSPWM_BORDER" 50 5 "#d3869b" "#d3869b" "#fbf1c7" "#b8bb26" 5 5 "$BSPWM_GAP"

		  killeww
		  launch polybar -q cata-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		
		melissa)
		
		  SetBspwmConf "$BSPWM_BORDER" 42 40 "#e5e9f0" "#e5e9f0" "#4c566a" "#bf616a" 5 5 "$BSPWM_GAP"

		  killeww
		  launch polybar -q mel-bar -c ${polydir}/config.ini
		  polybar -q mel2-bar -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		  
		pamela)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q pam1 -c ${polydir}/config.ini
		  polybar -q pam2 -c ${polydir}/config.ini &
		  polybar -q pam3 -c ${polydir}/config.ini &
		  polybar -q pam4 -c ${polydir}/config.ini &
		  polybar -q pam5 -c ${polydir}/config.ini &
		  polybar -q pam6 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		cristina)
		
		  SetBspwmConf "$BSPWM_BORDER" 10 60 "#9bced7" "#9bced7" "#c3a5e6" "#c3a5e6" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q cristina-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		z0mbi3)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 5 "#3d414f" "#3d414f" "#3d414f" "#90ceaa" 80 5 "$BSPWM_GAP"
		  
		  # Kill any running instances of bspc to prevent multiple
		  # instances of "workspaces" script in eww rices to run at once
		  killall -9 picom bspc
		  
		  launch eww -c $HOME/.config/bspwm/rices/z0mbi3/bar open bar
		  launch polybar -q tray -c ~/.config/bspwm/rices/z0mbi3/bar/polybar_tray.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		  karla)
		
		  SetBspwmConf "$BSPWM_BORDER" 65 5 "#ff004a" "#ff004a" "#0864f1" "#b93fe0" 5 5 "$BSPWM_GAP"
		 
		  kill -9 picom
		  launch eww -c $HOME/.config/bspwm/rices/karla/bar open bar
		  launch polybar -q karla-bar -c ${polydir}/config.ini
		  polybar -q karla-bar2 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-light
		  
		  ;;
		  
		andrea)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#161616" "#161616" "#605692" "#67d4f1" 5 5 "$BSPWM_GAP"
		  
		  killall -9 picom polybar
		  launch dunst -config ${bspdir}/dunstrc-light
		  launch eww -c $HOME/.config/bspwm/rices/$RICETHEME/arin --restart open-many \
		   search \
		   apps \
		   weather \
		   music \
		   system
		  
		  ;;
		  
	esac
	
##  ------------------------- workspaces config -------------------------  ##


# ----- Window rules ----- #
#  remove all rules first  #
bspc rule -r *:*


# ----- apps open in terminal workspaces ----- #

bspc rule -a Alacritty desktop='^1' follow=on focus=on


# ----- apps open in web workspaces ----- #

bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a Brave-browser desktop='^2' follow=on focus=on

#  free download manager  #
bspc rule -a Free desktop='^2' state=floating follow=on focus=on
bspc rule -a qBittorrent desktop='^2' state=floating follow=on focus=on

#  VPNs  #
bspc rule -a Windscribe2 desktop='^2' state=floating follow=on focus=on
bspc rule -a Protonvpn desktop='^2' state=floating follow=on focus=on


# ----- apps open in files workspaces ----- #

declare -a files=(Pcmanfm Thunar Caja dolphin)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done


# ----- apps open in code workspaces ----- #

declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done
   
bspc rule -a Code desktop ='^4' follow=on focus=on
bspc rule -a kate desktop ='^4' follow=on focus=on
bspc rule -a Leafpad desktop ='^4' follow=on focus=on
bspc rule -a github-desktop desktop ='^4' state=floating follow=on focus=on

#  jetBrains IDEs  #
bspc rule -a jetbrains-clion desktop ='^4' state=floating follow=on focus=on
bspc rule -a jetbrains-idea desktop ='^4' state=floating follow=on focus=on
bspc rule -a jetbrains-pycharm desktop ='^4' state=floating follow=on focus=on

#  Markdown editors  #
bspc rule -a inkdrop desktop ='^4' state=floating follow=on focus=on


# ----- apps open in entertainment workspaces ----- #

declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs vlc Spotify)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on; done


# ----- apps open in Communication workspaces ----- #

#declare -a comm=(Thunderbird TelegramDesktop Hexchat streamlink-twitch-gui discord)
#for i in ${comm[@]}; do
#   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# bspc rule -a Spotify desktop ='^7' state=floating follow=on focus=on

# ----- apps open in settings workspaces ----- #

bspc rule -a 'VirtualBox Manager' desktop='^6' follow=on focus=on
bspc rule -a GParted desktop='^6' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

bspc rule -a stacer desktop ='^6' state=floating follow=on focus=on
bspc rule -a Xsensors desktop ='^6' state=floating follow=on focus=on

########### bspwm conf

#bspc config external_rules_command ~/.config/bspwm/scripts/ExternalRules

bspc config single_monocle                true
bspc config split_ratio                   0.7
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16

########## AutoStart Apps

ReloadTerms
launch sxhkd -c ${bspdir}/sxhkdrc
launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf --fade-in-step=1 --fade-out-step=1 --fade-delta=0
#launch picom --legacy-backends --config ${bspdir}/rices/$RICETHEME/picom.conf
	
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

~/.fehbg &
#RandomWall
#nitrogen --restore &
xsetroot -cursor_name left_ptr
